- name: Create scaleset group
  hosts: localhost
  connection: local
  vars:
    state: present
  vars_files:
    - vars/vmss.yml

  tasks:
    - name: Get facts for all Public IPs within a resource groups
      azure_rm_publicipaddress_info:
        resource_group: "{{ rg_name }}"
      register: output_ip_address

    - name: Get loadbalancer info
      azure_rm_loadbalancer_info:
        resource_group: "{{ rg_name }}"
        name: "{{ lb_name }}"
      register: output

    - name: Add all hosts
      add_host:
        groups: scalesethosts
        hostname: "{{ output_ip_address.publicipaddresses[0].ip_address }}_{{ item.properties.frontendPort }}"
        ansible_host: "{{ output_ip_address.publicipaddresses[0].ip_address }}"
        ansible_port: "{{ item.properties.frontendPort }}"
        ansible_ssh_user: "{{ vm_user }}"
        ansible_ssh_key: "{{ ssh_pub_key }}"
      with_items:
        - "{{ output.ansible_info.azure_loadbalancers[0].properties.inboundNatRules }}"
