- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Return motd to registered var
      ansible.builtin.shell: ls -lah

    - name: Create resource group
      azure_rm_resourcegroup:
        name: rg-vpn-auto
        location: polandcentral
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: rg-vpn-auto
        name: vnet-vpn-auto
        address_prefixes: "10.0.0.0/16"
    - name: Add subnet
      azure_rm_subnet:
        resource_group: rg-vpn-auto
        name: subnet-vpn-auto
        address_prefix: "10.0.1.0/24"
        virtual_network: vnet-vpn-auto

    # - name: Public IP of VM
    #   debug:
    #     msg: "The public IP is {{ output_ip_address.state.ip_address }}."
    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: rg-vpn-auto
        name: sg-vpn-auto
        rules:
          - name: SSH
            protocol: TCP
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: Create VMSS
      azure_rm_virtualmachinescaleset:
        resource_group: rg-vpn-auto
        name: vmss-vpn-auto
        vm_size: Standard_B1s
        capacity: 1
        virtual_network_name: vnet-vpn-auto
        subnet_name: subnet-vpn-auto
        public_ip_per_vm: true
        terminate_event_timeout_minutes: 10
        admin_username: azureuser
        custom_data: vpn-auto.txt
        ssh_password_enabled: false
        security_group_name: sg-vpn-auto
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJvLOfoNgAvFLccYsDKicq8jduQoXk8J9fJ8TKuEwNPz
        managed_disk_type: Standard_LRS
        image:
          offer: 0001-com-ubuntu-server-jammy
          publisher: canonical
          sku: 22_04-lts-gen2
          version: latest
        state: present
      register: vm_result

    - name: Get facts for all virtual machines of a resource group
      azure_rm_virtualmachine_info:
        resource_group: rg-vpn-auto
