- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: rg-vpn-auto
        location: polandcentral
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: rg-vpn-auto
        name: vnet-vpn-auto
        address_prefixes: "10.0.0.0/16"
    - name: Add subnet
      azure_rm_subnet:
        resource_group: rg-vpn-auto
        name: subnet-vpn-auto
        address_prefix: "10.0.1.0/24"
        virtual_network: vnet-vpn-auto
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: rg-vpn-auto
        allocation_method: Static
        name: public-ip-vpn-auto
      register: output_ip_address
    - name: Public IP of VM
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}."
    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: rg-vpn-auto
        name: sg-vpn-auto
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: rg-vpn-auto
        name: nic-vpn-auto
        virtual_network: vnet-vpn-auto
        subnet: subnet-vpn-auto
        #public_ip_name: public-ip-vpn-auto
        security_group: sg-vpn-auto
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: rg-vpn-auto
        name: vm-vpn-auto
        vm_size: Standard_B1s
        admin_username: azureuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJvLOfoNgAvFLccYsDKicq8jduQoXk8J9fJ8TKuEwNPz"
        network_interfaces: nic-vpn-auto
        image:
          offer: 0001-com-ubuntu-server-jammy
          publisher: Canonical
          sku: 22_04-lts
          version: latest
        state: absent
