# Simple usage:
# ansible-playbook  vm.yml -e vmss_state=absent; ansible-playbook  vm.yml -e vmss_state=present; ssh az-vpn
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    state: absent
    vmss_state: absent

  vars_files:
    - vars/vmss.yml
    - vars/custom_data.yml

  tasks:
    - name: Return motd to registered var
      ansible.builtin.shell: ls -lah

    - name: Include core tasks - rg, vnet, sg, ip
      include_tasks: tasks/core_tasks.yml

    - name: Include app tasks - load balancer and vmss creation
      include_tasks: tasks/lb_vmss.yml

    - name: Include secrets - kv and secrets
      include_tasks: tasks/kv.yml
